### ISSUE TITLE
Interpolation Issues In Script Connecters

### ISSUE THREAD

**Issue by Bronnel721** [SorkinType/Briem-Hand#1]
![image](https://github.com/SorkinType/Briem-Hand/assets/92538982/79205d1d-ad8d-463b-b801-2d8c9fbd49b6)
These aren't the only ones, but these are some of them.

**Comment by EbenSorkin** [comment]
I'll be working on catching and fixing these this week.

Thanks!

-e.

**Comment by Bronnel721** [comment]
You're welcome.

**Comment by EbenSorkin** [comment]
Do you make fonts too?

-e.

**Comment by Bronnel721** [comment]
Yes. Some of them are uncompleted.

**Comment by EbenSorkin** [comment]
I'd love to see what you are making.

Have you shown them to Google fonts? Do you have any interest in that?

-e.

**Comment by Bronnel721** [comment]
I have not shown them. In fact, I don't even know if they'll accept them.

**Comment by EbenSorkin** [comment]
If you would like help with that or even to talk about non-libre font
licensing, feel free to let me know.

I am the art director @ Darden Studio. I also work on a lot of Google Fonts.

-e.

**Comment by Bronnel721** [comment]
Are you done interpolating the connectors, because if you are, `r.s` and `c.x` have yet to be fixed.

**Comment by EbenSorkin** [comment]
I think they are fixed in this most recent push.

**Comment by Bronnel721** [comment]
Yes, they are.

**Comment by EbenSorkin** [comment]
Thanks!

-e.

**Comment by Bronnel721** [comment]
You're welcome. Is it ready to use? Also, when you're ready, please update Briem Print.

**Comment by EbenSorkin** [comment]
Almost. It needs the extended language support reviewed.

**Comment by Bronnel721** [comment]
And the Greek and Cyrillic?

**Comment by EbenSorkin** [comment]
Those are stubs that could be expanded. They exist to support languages
that sometimes mix letters in from both scripts and because some letters
are shared and so you can fill those with trivial effort.

**Comment by Bronnel721** [comment]
So they exist for other languages in other scripts?

**Comment by EbenSorkin** [comment]
Joins are fixed
