### ISSUE TITLE
LATIN SMALL LETTER dz doesn't join (should it?)

### ISSUE THREAD

**Issue by simoncozens** [SorkinType/Briem-Hand#5]
```
*$ shape fonts/variable/BriemHand\[wght\].ttf 'ǳ'
[gid455=0+1085]
```
![shape](https://github.com/SorkinType/Briem-Hand/assets/106728/bb7a3fdc-43bf-4eaa-a792-74aee1659825)

**Comment by EbenSorkin** [comment]
In the non-joining version it should not. But IDK about in the joining version. I'd better ask Denis. But as a practical matter we would have to intervene manually or make a script to pick the correct glyph and sub it in like we sometimes do with the dollar sign. Given the relative importance of this which is I think ( correct me if I have this wrong) fairly low ( it is used for translitteration of Cyrillic only I think) maybe not worth worrying about.
